{% set name = "arrakis-python" %}
{% set pypi_name = "arrakis" %}
{% set version = "0.4.0" %}

{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/arrakis-{{ version }}.tar.gz
  sha256: 3099e5fd1e6e1c5fae7b05f3cdccfa517f876f98b7e6653315aca1109be87e96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - gpstime
    - jsonschema
    - libarrow-flight
    - numpy
    - pyarrow
    - python >={{ python_min }}
    - python-arrakis-schema >=0.1
    - python-confluent-kafka >=1.8
    - typing_extensions

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -m pip check
    - python -m pip show {{ pypi_name }}
    - python -m pytest -ra -v --pyargs arrakis

about:
  home: https://git.ligo.org/ngdd/arrakis-python
  dev_url: https://git.ligo.org/ngdd/arrakis-python
  doc_url: https://docs.ligo.org/ngdd/arrakis-python
  summary: Arrakis Python client library
  license: LGPL-3.0-or-later
  license_file: LICENSE
  description: |
    ## Features

    - Query live and historical timeseries data
    - Describe channel metadata
    - Search for channels matching a set of conditions
    - Publish timeseries data

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
    - myNameIsPatrick
