schema_version: 1

context:
  version: "0.19.0"

package:
  name: arrakis-python
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/a/arrakis/arrakis-${{ version }}.tar.gz
  sha256: 05cc52cf8e730e52192e78687b4536228b05bcb5aec2a71239cf445ed2fbbe7d

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - gpstime >=0.9
    - igwn-auth-utils >=1.0
    - jsonschema
    - libarrow-flight
    - numpy
    - pyarrow
    - python >=${{ python_min }}
    - python-arrakis-schema 0.5.*
    - python-confluent-kafka >=1.8
    - rich
    - sympy
    - typing_extensions

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - pytest
        - pytest-console-scripts
        - pytest-freezer
        - pytest-timeout
    script:
      - python -m pip check
      - python -m pip show arrakis
      - python -m pytest -ra -v --pyargs arrakis -k "not test_publish"

about:
  summary: Arrakis Python client library
  description: |
    ## Features

    - Query live and historical timeseries data
    - Describe channel metadata
    - Search for channels matching a set of conditions
    - Publish timeseries data
  homepage: https://git.ligo.org/ngdd/arrakis-python
  repository: https://git.ligo.org/ngdd/arrakis-python
  documentation: https://docs.ligo.org/ngdd/arrakis-python
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
    - nothisisolivia
